export const c = {
    USER_LOGIN: "USER_LOGIN",
    LOAD_MOVIES: "LOAD_MOVIES",
    LOAD_MOVIE: "LOAD_MOVIE",
    SEARCH_MOVIE: "SEARCH_MOVIE",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}

export default c;